source/api/urls.py
from django.urls import path

from api.views import add_view, subtract_view, multiply_view, divide_view

app_name = 'api'

urlpatterns = [
    path('add/', add_view, name='add'),
    path('subtract/', subtract_view, name='sub'),
    path('multiply/', multiply_view, name='mul'),
    path('divide/', divide_view, name='div'),
]

source/main/urls.py
from django.contrib import admin
from django.urls import path, include

from webapp.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('', IndexView.as_view(), name='index')
]

source/webapp/models.py
from django.db import models

# Create your models here.

source/api/views.py
import json

from django.http import JsonResponse


def add_view(request, *args, **kwargs):
    if request.body:
        data = json.loads(request.body)
        try:
            answer = float(data['A']) + float(data['B'])
        except Exception as e:
            return JsonResponse({'error': str(e)})
        return JsonResponse({'result': str(answer)})


def subtract_view(request, *args, **kwargs):
    if request.body:
        data = json.loads(request.body)
        try:
            answer = float(data['A']) - float(data['B'])
        except Exception as e:
            return JsonResponse({'error': str(e)})
        return JsonResponse({'result': str(answer)})


def multiply_view(request, *args, **kwargs):
    if request.body:
        data = json.loads(request.body)
        try:
            answer = float(data['A']) * float(data['B'])
        except Exception as e:
            return JsonResponse({'error': str(e)})
        return JsonResponse({'result': str(answer)})


def divide_view(request, *args, **kwargs):
    if request.body:
        data = json.loads(request.body)
        try:
            answer = float(data['A']) / float(data['B'])
        except Exception as e:
            return JsonResponse({'error': str(e)})
        return JsonResponse({'result': str(answer)})

source/webapp/views.py
from django.shortcuts import render
from django.views.generic import View


class IndexView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'index.html')

source/webapp/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<div class="container">
    <form method="post">
        {% csrf_token %}
        <label>
            Число "А":
            <input id="A" type="text" class="input">
        </label>

        <label>
            Число "Б":
            <input id="B" type="text" class="input">
        </label>
        <br>
        <a type="submit" href="{% url 'api:add' %}" data-target="add" class="btn">Сложить</a>
        <a type="submit" href="{% url 'api:sub' %}" data-target="sub" class="btn">Вычесть</a>
        <a type="submit" href="{% url 'api:mul' %}" data-target="mul" class="btn">Умножить</a>
        <a type="submit" href="{% url 'api:div' %}" data-target="div" class="btn">Разделить</a>
    </form>
    <div class="result"></div>
</div>

    <script type="application/javascript" src="{% static 'js/main.js' %}"></script>
</body>
</html>